name: game_paper_clic
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  percent_indicator: ^4.2.3
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/coal.png
    - assets/images/copper-ore.png
    - assets/images/iron-ore.png
    - assets/images/wood.png
    - assets/images/money.png
    - assets/images/miner.png
    - assets/images/money.gif
    - assets/data.json
    - assets/images/receipes/axe.png
    - assets/images/receipes/pickaxe.png
    - assets/images/receipes/copper-ingot.png
    - assets/images/receipes/iron-ingot.png
    - assets/images/receipes/metal-rod.png
    - assets/images/receipes/electric-wire.png
    - assets/images/receipes/mine.png
    - assets/images/receipes/foundry.png
    - assets/images/receipes/iron-plate.png


